### ISSUE TITLE
Batter runs only counted on homeruns

### ISSUE THREAD

**Issue by harvitronix** [calestini/retrosheet#3]
It appears as though the "run" batter statistic is only incremented on homers in the new parser.

**Comment by harvitronix** [comment]
My mistake. Runs are only attributed to batter statistics in the at-bat event itself. Others are recorded in running stats. Carry on!

**Comment by calestini** [comment]
Hi @harvitronix ,

Sorry had some time off the scripts. As the season started, I am hoping to get back to it very soon, including refactoring a bit the code for reducing complexity.
